### ISSUE TITLE
Aliases of private services do not respect privacy

### ISSUE THREAD

**Issue by downsider** [silktide/syringe#33]
This concerns aliases of private services _within the same namespace_; aliasing a private service from another namespace will not work (as you would expect).

This is an edge case that will rarely be an issue, but either needs documenting or correcting. If you have an alias of a private service (all within the same namespace), the current behaviour exposes that alias to the container without obfuscating it's key. A service in another namespace can then reference the alias and access a service that was meant to be private.

```yml
#private.yml - aliased with "private"
services:
    privateService:
        #...
        private: true

    privateAlias:
        aliasOf: "@privateService"
```

```yml
#public.yml
services:
    failingService:
        #...
        arguments:
            - "@private.privateService" # This will fail as expected

    ignorePrivacyService:
        #...
        arguments:
            - "@private.privateAlias" # This works when it shouldn't
```
